### ISSUE TITLE
Resolve refs to input files relative to an input directory

### ISSUE THREAD

**Issue by drmalex07** [OpertusMundi/ingest#1]
When input is given as a reference to a file it must be resolved as a relative path against an input directory. 
The input directory itself must be given as an environment variable `INPUT_DIR` of the service.

**Comment by drmalex07** [comment]
Now, the input file is assumed to be an absolute file path (which is not practical in cases that the service is running inside a container).

See also:
https://github.com/OpertusMundi/ingest/blob/master/ingest/app.py#L423

**Comment by pmitropoulos** [comment]
Closed with d7a24a3430695912854cd4fd95ea57c0c0c9ea00
